-- =====================================================================
-- verity_schema.sql — Verity v2 canonical schema · LOADER
-- One file per object under reference/ core/ audit/. Loaded in dependency order;
-- cross-domain FKs applied last (core/_relationships.sql). Target: PostgreSQL 18+.
-- =====================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS reference;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS audit;
SET search_path = core, reference, audit, public;

\i reference/actor_type.sql
\i reference/role.sql
\i reference/executable_kind.sql
\i reference/capability_type.sql
\i reference/trust_level.sql
\i reference/data_classification.sql
\i reference/governance_tier.sql
\i reference/version_change_type.sql
\i reference/api_role.sql
\i reference/tool_transport.sql
\i reference/source_kind.sql
\i reference/connector_type.sql
\i reference/binding_delivery_mode.sql
\i reference/write_mode.sql
\i reference/lifecycle_state.sql
\i reference/approval_request_status.sql
\i reference/approval_decision.sql
\i reference/intake_status.sql
\i reference/ai_risk_tier.sql
\i reference/naic_materiality.sql
\i reference/materiality_tier.sql
\i reference/requirement_kind.sql
\i reference/requirement_status.sql
\i reference/artifact_plan_status.sql
\i reference/app_team_role.sql
\i reference/derivation_method.sql
\i reference/governance_domain.sql
\i reference/control_phase.sql
\i reference/control_type.sql
\i reference/enforcement_action.sql
\i reference/evidence_artifact_type.sql
\i reference/coverage_level.sql
\i reference/exception_status.sql
\i reference/model_status.sql
\i reference/currency.sql
\i reference/run_purpose.sql
\i reference/quota_scope_type.sql
\i reference/quota_period.sql
\i reference/quota_enforcement_mode.sql
\i reference/quota_alert_level.sql
\i reference/harness_variant.sql
\i reference/environment_kind.sql
\i reference/deployment_channel.sql
\i reference/deployment_run_mode.sql
\i reference/deployment_operation.sql
\i reference/deployment_outcome.sql
\i reference/deployment_status.sql
\i reference/harness_instance_status.sql
\i reference/health_status.sql
\i reference/heartbeat_kind.sql
\i reference/command_kind.sql
\i reference/command_status.sql
\i reference/embedding_runtime.sql
\i reference/report_kind.sql
\i reference/report_run_status.sql
\i reference/gt_dataset_status.sql
\i reference/gt_quality_tier.sql
\i reference/gt_source_type.sql
\i reference/gt_annotator_type.sql
\i reference/mock_kind.sql
\i reference/validation_run_status.sql
\i reference/validation_match_type.sql
\i reference/extraction_field_type.sql
\i reference/extraction_match_type.sql
\i reference/tolerance_unit.sql
\i reference/incident_severity.sql
\i reference/incident_status.sql
\i reference/evaluation_type.sql
\i reference/model_card_state.sql
\i reference/setting_input_type.sql
\i core/actor.sql
\i core/account_user.sql
\i core/automation_actor.sql
\i core/actor_role_grant.sql
\i core/current_actor_role.sql
\i core/executable.sql
\i core/inference_config.sql
\i core/executable_version.sql
\i core/prompt.sql
\i core/prompt_version.sql
\i core/tool.sql
\i core/tool_version.sql
\i core/data_connector.sql
\i core/data_connector_version.sql
\i core/mcp_server.sql
\i core/mcp_server_version.sql
\i core/executable_prompt_assignment.sql
\i core/executable_tool_assignment.sql
\i core/executable_mcp_assignment.sql
\i core/source_binding.sql
\i core/target_binding.sql
\i core/lifecycle_event.sql
\i core/entity_lifecycle_current.sql
\i core/champion_assignment.sql
\i core/entity_champion_current.sql
\i core/approval_request.sql
\i core/approval_signoff.sql
\i core/application.sql
\i core/intake.sql
\i core/intake_requirement.sql
\i core/intake_impact_assessment.sql
\i core/intake_impact_assessment_current.sql
\i core/intake_artifact_plan.sql
\i core/intake_artifact_plan_estimate.sql
\i core/intake_roi_assessment.sql
\i core/intake_cost_envelope.sql
\i core/intake_entity_link.sql
\i core/intake_obligation_resolution.sql
\i core/intake_obligation.sql
\i core/actor_app_role_grant.sql
\i core/current_actor_app_role.sql
\i core/regulatory_framework.sql
\i core/regulatory_provision.sql
\i core/canonical_requirement.sql
\i core/requirement_tier.sql
\i core/control.sql
\i core/evidence_specification.sql
\i core/provision_requirement.sql
\i core/requirement_control.sql
\i core/compliance_exception.sql
\i core/domain_maturity.sql
\i core/domain_maturity_current.sql
\i audit/decision_status.sql
\i audit/invocation_status.sql
\i audit/auth_event_type.sql
\i audit/auth_event_outcome.sql
\i core/model.sql
\i core/model_price.sql
\i core/model_reference.sql
\i core/model_reference_binding.sql
\i core/inference_config_model.sql
\i audit/decision_log.sql
\i audit/model_invocation_log.sql
\i audit/v_model_invocation_cost.sql
\i audit/evidence.sql
\i audit/status_transition.sql
\i audit/auth_event.sql
\i core/hitl_override.sql
\i core/run_status.sql
\i core/run_completion_status.sql
\i core/run_entity_kind.sql
\i core/outbox_status.sql
\i core/execution_run.sql
\i core/execution_run_status.sql
\i core/execution_run_current.sql
\i core/run_dispatch_outbox.sql
\i core/quota.sql
\i core/quota_check.sql
\i core/harness_image.sql
\i core/deployment_environment.sql
\i core/deployment_cluster.sql
\i core/harness_instance.sql
\i core/harness_instance_command.sql
\i audit/harness_heartbeat.sql
\i audit/harness_instance_health_current.sql
\i audit/harness_running_package_current.sql
\i core/package.sql
\i core/package_harness_compatibility.sql
\i core/deployment.sql
\i core/deployment_event.sql
\i core/deployment_connection.sql
\i core/deployment_binding_override.sql
\i core/lifecycle_deployment_rule.sql
\i core/embedding_config.sql
\i core/report_definition.sql
\i core/report_field.sql
\i audit/report_run_log.sql
\i core/test_suite.sql
\i core/test_case.sql
\i core/test_case_mock.sql
\i core/ground_truth_dataset.sql
\i core/ground_truth_record.sql
\i core/ground_truth_record_mock.sql
\i core/ground_truth_annotation.sql
\i core/validation_run.sql
\i core/validation_record_result.sql
\i core/evaluation_run.sql
\i core/model_card.sql
\i core/metric_threshold.sql
\i core/field_extraction_config.sql
\i core/incident.sql
\i core/platform_settings.sql
\i audit/test_execution_log.sql
\i audit/description_similarity_log.sql
\i core/_relationships.sql
